const userCommerceData = [
  {
    id: "123432",
    name: "Anderson Lopez",
    email: "lopezanderson069@gmail.com",
    state: "Activo",
    card: "Gold",
    number: "4.3",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 34532,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "2123432",
    name: "Braiyan Rodriguez",
    email: "braiyan@gmail.com",
    state: "Activo",
    card: "Blue",
    number: "4.9",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 123,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "3123432",
    name: "Elian Jhon",
    email: "elian@gmail.com",
    state: "Activo",
    card: "Blue",
    number: "6.0",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 324,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "4123432",
    name: "Eliezer Lopez",
    email: "eliezer@gmail.com",
    state: "Activo",
    card: "Black",
    number: "4.0",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 567,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "5123432",
    name: "Melmira Mirian",
    email: "melmira@gmail.com",
    state: "Activar",
    card: "Blue",
    number: "3.9",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 864,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "6123432",
    name: "Nathan Champes",
    email: "nathan@gmail.com",
    state: "Activar",
    card: "Gold",
    number: "6.5",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 324,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "7123432",
    name: "Maiborys Milñi",
    email: "maiborys@gmail.com",
    state: "Activo",
    card: "Black",
    number: "4.3",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 673234,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "8123432",
    name: "Juan Camilo",
    email: "juan@gmail.com",
    state: "Activo",
    card: "Gold",
    number: "0.0",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 8456,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "9123432",
    name: "KitKat",
    email: "kitKat@gmail.com",
    state: "Activar",
    card: "Black",
    number: "7.0",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 2983,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "10123432",
    name: "Jean Carlos",
    email: "jean@gmail.com",
    state: "Activo",
    card: "Blue",
    number: "0.0",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 6723,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "11123432",
    name: "Marol Nean",
    email: "marol@gmail.com",
    state: "Activar",
    card: "Black",
    number: "2.0",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 734,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "12123432",
    name: "Morgan Nevean",
    email: "morgan@gmail.com",
    state: "Activo",
    card: "Gold",
    number: "37.0",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 723,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
  {
    id: "13123432",
    name: "Humberto Norean",
    email: "humberto@gmail.com",
    state: "Activar",
    card: "Blue",
    number: "4.0",
    img: "/img/image/gatodenegocios.jpeg",
    department: "Cundinamarca",
    city: "Bogotá",
    phone: "3242574768",
    coverage: "Nacional",
    expiration: "07/2027",
    pointspocket: 732,
    favorites: [
      {
        id: "ortodentis",
        category: "Bienestar",
        title: "ORTODENTIS",
      },
      {
        id: "gmo",
        category: "Bienestar",
        title: "GMO",
      },
      {
        id: "dentisalud",
        category: "Bienestar",
        title: "DENTISALUD",
      },
      {
        id: "beer",
        category: "Diversion",
        title: "BEER",
      },
      {
        id: "lamontañatitos",
        category: "Diversion",
        title: "BOLERA LA MONTAÑA TITOS",
      },
      {
        id: "multibolo",
        category: "Diversion",
        title: "BOLERA MULTIBOLO",
      },
      {
        id: "smart",
        category: "Estudiar",
        title: "ACADEMIA SMART",
      },
      {
        id: "chiper",
        category: "Hogar",
        title: "CHIPER S.A.S",
      },
      {
        id: "amoresperros",
        category: "Mascotas",
        title: "AMORES PERROS",
      },
      {
        id: "bame",
        category: "Seguridad",
        title: "BAME",
      },
      {
        id: "afraniuz",
        category: "Shopping",
        title: "AFRANIUZ",
      },
      {
        id: "auapp",
        category: "Transporte",
        title: "AUAPP",
      },
      {
        id: "alquilerdevehiculo",
        category: "Viajar",
        title: "ALQUILER DE VEHICULO",
      },
      {
        id: "expresopazderios",
        category: "Viajar",
        title: "EXPRESO PAZ DE RIOS.A",
      },
      {
        id: "flotamagdalena",
        category: "Viajar",
        title: "FLOTA MAGDALENA",
      },
    ],
  },
];

export default userCommerceData;
